[package]
name = "gfm-index"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
gfm-content = { path = "../content" }
gfm-fs = { path = "../fs" }
gfm-jobs = { path = "../jobs" }
gfm-search = { path = "../search" }
gfm-store = { path = "../store" }
gfm-types = { path = "../types" }

[lints]
workspace = true
