[package]
name = "gfm"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
gfm-config = { path = "../config" }
gfm-content = { path = "../content" }
gfm-fs = { path = "../fs" }
gfm-index = { path = "../index" }
gfm-jobs = { path = "../jobs" }
gfm-mac = { path = "../mac" }
gfm-ops = { path = "../ops" }
gfm-packaging = { path = "../packaging" }
gfm-store = { path = "../store" }
gfm-testkit = { path = "../testkit" }
gfm-types = { path = "../types" }

[dev-dependencies]
zip = { version = "4.3.0", default-features = false, features = ["deflate"] }

[lints]
workspace = true
