[package]
name = "gfm-ops"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
filetime = "0.2.29"
gfm-fs = { path = "../fs" }
gfm-types = { path = "../types" }
libc = "0.2.177"
rustix = { version = "1.1.4", features = ["fs"] }
trash = "5.2.6"
xattr = "1.6.1"

[lints]
workspace = true
